### ISSUE TITLE
please improve the moodle.org plugins db description

### ISSUE THREAD

**Issue by danmarsden** [EsdrasCaleb/moodle-tool_sentry#2]
eg  what is sentry, why would someone install your plugin, what useful functionality does the plugin provide?

**Comment by danmarsden** [comment]
.. is sentry "free" - do you have to have a subscription? - can you host it yourself etc etc.

**Comment by EsdrasCaleb** [comment]
I put it in version.php thx

**Comment by danmarsden** [comment]
you seem to misunderstand - in the moodle.org plugins database, there is a description field that describes your plugin. This is what needs to be improved to cover the information I state above - you have not yet fixed this up, so you should not have closed this.

![Screenshot from 2023-05-18 09-24-41](https://github.com/EsdrasCaleb/moodle-tool_sentry/assets/362798/a12f0188-3cbf-42f8-9577-566716d88200)

**Comment by EsdrasCaleb** [comment]
Oh thx you meaned inside the description

**Comment by danmarsden** [comment]
yes - the description in the moodle.org plugins db (shown in the screenshot I attached above)
Should include information that explains what sentry is, why would someone install your plugin, what useful functionality does the plugin provide,  is sentry "free" - do you have to have a subscription? - can you host it yourself etc etc.

none of that information has been added yet that I can see.

**Comment by EsdrasCaleb** [comment]
hi I updated in the git and in the plugin new version. I saw now that I did not updated in plugin description. I corrected this now. Thank you for the support
