### ISSUE TITLE
missing privacy api.

### ISSUE THREAD

**Issue by danmarsden** [EsdrasCaleb/moodle-tool_sentry#3]
Moodle uses a privacy API for GDPR compliance to allow plugins to specify how they deal with user data. Your plugin appears to pass information to an external service so privacy api compliance is a requirement for approval in the plugins db.

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

I suspect your plugin passes user information to the external api - so please pay close attention to the requirements around this in the privacy api docs:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

**Comment by EsdrasCaleb** [comment]
it passes a page and the ip that accessed it does not pass user info. It's a plugin that contacts the sentry.io to send the errors that a site has. It is useful to track when a service is having problems before the user reports it.
I will add a null provider
